name: build-and-deploy
on:
    push:
        branches:
            - master
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
            - run: npm i -g surge
            - run: npm i
            - name: "Build"
              run: npx gatsby build
              env: 
                GOOGLE_CLIENT_EMAIL: ${{ secrets.GOOGLE_CLIENT_EMAIL }}
                GOOGLE_PRIVATE_KEY: ${{ secrets.GOOGLE_PRIVATE_KEY }}
                GOOGLE_DRIVE_FOLDER_ID: ${{ secrets.GOOGLEDRIVEFOLDERID }}
            - name: "Deploy"
              run: surge public ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_DEPLOY_TOKEN }}