name: build-and-deploy
on:
    push:
        branches:
            - master
    repository_dispatch:
        types: [datocms_deploy_request]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
            - run: npm i -g surge
            - run: npm i
            - name: "Build"
              run: npx gatsby build
              env: 
                DATO_CMS_API_TOKEN: ${{ secrets.DATO_CMS_API_TOKEN }}
            - name: "Deploy"
              run: surge public ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_DEPLOY_TOKEN }}
            - name: "Notify DatoCMS of success"
                if: ${{ success() }}
                uses: wei/curl@v1
                with:
                    args: -n -X POST https://webhooks.datocms.com/${{ secrets.DATO_CMS_NOTIFY_HASH }}/deploy-results -H 'Content-Type: application/json' -d '{ "status": "success" }'
            - name: "Notify DatoCMS of failure"
              if: ${{ failure() }}
              uses: wei/curl@v1
              with:
                  args: -n -X POST https://webhooks.datocms.com/${{ secrets.DATO_CMS_NOTIFY_HASH }}/deploy-results -H 'Content-Type: application/json' -d '{ "status": "error" }'
